language: node_js
node_js:
  - "4"
sudo: false
services:
  - rabbitmq
script:
  - npm run lint
  - npm run coverage
  - npm run unit
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
after_success:
  - npm run codeclimate
