var fromGithub = ["jaredhobbs",
"erichurkman",
"josh-io",
"kyle-eshares",
"asilachev",
"tizz98",
"alexandrelaplante",
"williamscales",
"youngah89",
"lemongod",
"estesmax",
"luismmontielg",
"dduong42",
"estherrasche",
"GilmarLira",
"viniciustelesbezerra",
"GreenMonkeySaveEarth",
"jairvercosa",
"cfloth",
"saechtner",
"roddds",
"henward0",
"fjsj",
"mikesierra",
"tim5046",
"danielgouvea",
"andersonresende",
"johnboy55",
"delimatorres",
"romulocollopy",
"caeleanb",
"lvieirajr",
"pbassut",
"victorcarrico",
"eshares-chris",
"bhardin",
"diofeher",
"theomiller",
"chrisburnor",
"LucianaNasr",
"marcoamorales",
"edisonsalman",
"hmln",
"tktnguyen",
"seelyrabbit",
"brad-eshares",
"kangaroosterus",
"gregory-nisbet",
"bfmonteiro",
"hansonkd",
"caamiillaa",
"renatonouman",
"interactivedocs",
"kaliuee",
"cuppaosh"];

var fromRunnable = ["bhardin",
"johnboy55",
"erichurkman",
"estherrasche",
"williamscales",
"dduong42",
"luismmontielg",
"lemongod",
"saechtner",
"jairvercosa",
"romulocollopy",
"GreenMonkeySaveEarth",
"jausto",
"edisonsalman",
"theomiller",
"youngah89",
"josh-io",
"kangaroosterus",
"danielgouvea",
"delimatorres",
"alexandrelaplante",
"jaredhobbs",
"tktnguyen",
"estesmax",
"tizz98",
"viniciustelesbezerra",
"eshares-chris",
"GilmarLira",
"tim5046",
"caeleanb",
"lvieirajr",
"bfmonteiro",
"pbassut",
"bfmonteiro",
"seelyrabbit",
"renatonouman",
"roddds",
"kyle-eshares"];

// fromRunnable.forEach(function (run) {

// });

console.log(isItInGithub("tizz98"));

var isItInGithub = function (s) {
	fromGithub.forEach(function (git) {
		if (git == s)
			return true;
	});

	return false;
}